import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {marked}=require('C:/Users/백창현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked/lib/marked.esm.js');
const D=path.dirname(fileURLToPath(import.meta.url));
const template=fs.readFileSync(path.join(D,'report.template.md'),'utf8');
const body=template.replace(/<!-- INCLUDE ([^ ]+) -->/g,(_,p)=>fs.readFileSync(path.join(D,p),'utf8').replace(/^\uFEFF/,''));
fs.writeFileSync(path.join(D,'report.md'),body,'utf8');
const files=['report.md','claim_comparison.md','technical_appendix.md','README.md',...fs.readdirSync(path.join(D,'tables')).filter(n=>n.endsWith('.md')).map(n=>'tables/'+n)];
const css=`*{box-sizing:border-box}body{background:#f3f6f5;color:#203b43;font-family:'Malgun Gothic',sans-serif;margin:0;line-height:1.9}main{max-width:960px;margin:28px auto;padding:45px 50px;background:white}h1{font-size:32px;line-height:1.45}h2{margin-top:65px;padding:16px;background:#e6f1ed;border-top:3px solid #287970;font-size:25px;line-height:1.6}h3{margin-top:35px;padding-left:12px;border-left:3px solid #87aaa5;font-size:21px}p,li{font-size:18px}a{color:#126d79;overflow-wrap:anywhere}strong{color:#103e41}img{display:block;width:100%;height:auto;margin:30px auto 10px}figure{margin:30px 0;max-width:100%}.figure-scroll{overflow-x:auto}.figure-scroll.zoomed a{display:block;width:900px}.figure-toggle{font:inherit;font-size:14px;color:#126d79;background:#eef6f3;border:1px solid #a7c7bf;border-radius:5px;padding:8px 12px;cursor:pointer}blockquote{margin:22px 0;padding:12px 18px;border-left:4px solid #ac7b4d;background:#fbf5ea}blockquote p{font-size:15px}.caption,p:has(>em:only-child){font-size:15px;color:#596b70}em{font-style:normal}nav,details{font-size:15px;background:#f0f5f4;padding:18px;margin:22px 0}nav{display:flex;gap:18px;flex-wrap:wrap}details ul li{font-size:15px}.table-wrap{overflow-x:auto;margin:25px 0}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.7}th,td{border:1px solid #d4dfdc;padding:11px;text-align:left;vertical-align:top}th{background:#e7f0ed}tbody tr:nth-child(even){background:#f7faf9}code{overflow-wrap:anywhere}pre{overflow-x:auto;font-size:13px;background:#f1f3f5;padding:16px}.note{padding:17px;border-left:4px solid #ac7b4d;background:#fbf5ea;font-size:15px}h2,h3{scroll-margin-top:18px}@media(max-width:650px){main{margin:0;padding:23px 18px}h1{font-size:27px}h2{font-size:23px}h3{font-size:20px}p,li{font-size:17px}.table-wrap{overflow:visible}table.wide,table.wide tbody,table.wide tr,table.wide td{display:block;width:100%}table.wide thead{display:none}table.wide tr{margin-bottom:16px;border:1px solid #bcd1cd;border-radius:6px;padding:7px;background:#f8fbfa}table.wide td{border:0;border-bottom:1px solid #e0e8e6;font-size:15px;padding:8px}table.wide td:before{content:attr(data-label);display:block;font-weight:700;color:#19615f;font-size:13px}table:not(.wide){font-size:12px}th,td{padding:7px}details li{word-break:keep-all}img{margin-top:20px}nav{gap:12px}}`;
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
for(const name of files){
 const src=fs.readFileSync(path.join(D,name),'utf8').replace(/^\uFEFF/,'');let html=marked.parse(src);let i=0;const toc=[];
 html=html.replace(/<h([23])>(.*?)<\/h\1>/g,(_,level,title)=>{const id='s'+(++i);if(level==='2')toc.push(`<li><a href="#${id}">${title}</a></li>`);return `<h${level} id="${id}">${title}</h${level}>`;});
 html=html.replace(/<table>([\s\S]*?)<\/table>/g,(_,t)=>{const headers=[...t.matchAll(/<th[^>]*>(.*?)<\/th>/gs)].map(x=>x[1].replace(/<[^>]+>/g,''));t=t.replace(/<tr>([\s\S]*?)<\/tr>/g,(all,row)=>{let j=0;return '<tr>'+row.replace(/<td([^>]*)>/g,(_,a)=>`<td${a} data-label="${esc(headers[j++]||'')}">`)+'</tr>';});return `<div class="table-wrap"><table class="${headers.length>=4?'wide':''}">${t}</table></div>`;});
 html=html.replace(/<p>(<img[^>]+>)<\/p>/g,(_,img)=>`<figure><button class="figure-toggle" type="button" aria-expanded="false" onclick="const box=this.nextElementSibling;const expanded=box.classList.toggle('zoomed');this.setAttribute('aria-expanded',expanded);this.textContent=expanded?'그림 축소 · 좌우로 밀어 읽기':'그림 확대해서 읽기';">그림 확대해서 읽기</button><div class="figure-scroll"><a href="${img.match(/src="([^"]+)"/)[1]}" target="_blank" aria-label="그림 원본 크게 보기">${img}</a></div></figure>`);
 html=html.replace(/href="([^"#]+\.md)(#[^"]*)?"/g,(all,ref,frag='')=>{const target=path.resolve(D,path.dirname(name),ref);return files.some(f=>path.resolve(D,f)===target)?`href="${ref.slice(0,-3)}.html${frag}"`:all;});
 const prefix=name.startsWith('tables/')?'../':'';
 const title=src.split('\n')[0].replace(/^#+ /,'');
 const nav=`<nav><a href="${prefix}report.html">전체 보고서</a><a href="${prefix}claim_comparison.html">문구 제안</a><a href="${prefix}technical_appendix.html">기술 부록</a><a href="${prefix}README.html">파일·재현 안내</a></nav>`;
 const page=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${css}</style></head><body><main>${nav}<p class="caption">Baseline · 2026-09-28 · 기존 원고를 보존한 확장 비교 보고서</p>${toc.length?`<details><summary>목차 열기</summary><ul>${toc.join('')}</ul></details>`:''}${html}${nav}</main></body></html>`;
 fs.writeFileSync(path.join(D,name.replace(/\.md$/,'.html')),page,'utf8');
}
console.log(JSON.stringify({rendered:files,figures:5}));
