"""Create a new evidence index for the methodology/derived-report subreview only."""
from pathlib import Path
import sys, json, hashlib, datetime, platform
ROOT=Path('C:/Users/백창현/Desktop/Baseline');HERE=Path(__file__).resolve().parent
def meta(p):
    p=Path(p);h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(4*1024*1024),b''):h.update(b)
    return {'path':p.relative_to(ROOT).as_posix(),'sha256':h.hexdigest(),'bytes':p.stat().st_size}
files=['AGENTS.md','README.md','guides/analysis.md','models/registry.md','columns/001-ball-count/column.md','columns/001-ball-count/sources.md','columns/001-ball-count/analysis/bcap_request_original.txt','columns/001-ball-count/analysis/handoff_bcap_review.md','columns/001-ball-count/analysis/bcap_v010_report_20260909.md','models/bcap/README.md','models/bcap/design_decisions.md','models/bcap/measurement_review.md','models/bcap/run.py','models/bcap/data.py','models/bcap/refit_stability.py','models/bcap/build_report.py','models/bcap/supplement_diagnostics.py','columns/001-ball-count/analysis/bcap_implementation_review_20260909/verify_bootstrap.py','columns/001-ball-count/analysis/bcap_implementation_review_20260909/review.md','columns/001-ball-count/analysis/bcap_implementation_review_20260909/compare_existing_estimates.py']
files += [f'models/bcap/{v}/v0.1.0/{name}' for v in ['pitch','swing'] for name in ['model_card.md','specification.yaml','validation.md']]
record={'indexed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'role':'Methodology review and source-aggregate/bootstrap/report independent subreview evidence','inputs_current_hashes':[meta(ROOT/p) for p in files],'historical_limit':'These document hashes index currently read sources; no past non-modification claim is inferred solely from current hashes. Bootstrap/report manifests separately compare explicit historical hashes.','document_read_scope':'Original/review requests and methodology/engine/refit read; report generator and supplement definitions inspected; data.py targeted action/selection/lag code references; column/source operational context reviewed. Main provenance/raw/nuisance inspections belong to other subreviews.','commands':[{'command':[sys.executable,'-B',str(HERE/'bootstrap_audit.py')],'execution_class':'reaggregate_existing_summaries; reconstruct game draws/split hashes/training N; no fitting','evidence':'bootstrap_evidence_manifest.json'},{'command':[sys.executable,'-B',str(HERE/'report_tables_audit.py')],'execution_class':'reaggregate/crosscheck original tables and rebuild behavior d/proportions; no fitting','evidence':'report_tables_evidence_manifest.json'},{'command':[sys.executable,'-B',str(Path(__file__).resolve())],'execution_class':'evidence_index_only'}],'environment':{'python':platform.python_version(),'platform':platform.platform(),'bytecode_disabled':sys.dont_write_bytecode},'outputs':[meta(p) for p in sorted(HERE.iterdir()) if p.is_file()],'web_evidence':'literature_sources.json records actual readable primary sections and failed fulltext attempts; no raw play collection','no_actions':['existing model/run/source/report modified','model refit','new external model evaluation','SWING2026 evaluation','KBO','Drive','external publication']}
with (HERE/'methodology_evidence_manifest.json').open('x',encoding='utf-8') as f:json.dump(record,f,ensure_ascii=False,indent=2)
print(json.dumps({'status':'COMPLETE','indexed_inputs':len(files),'indexed_outputs':len(record['outputs'])},ensure_ascii=False))
